export const FETCH_SELLER_ORDERS_REQUEST = 'FETCH_SELLER_ORDERS_REQUEST';
export const FETCH_SELLER_ORDERS_SUCCESS = 'FETCH_SELLER_ORDERS_SUCCESS';
export const FETCH_SELLER_ORDERS_FAILURE = 'FETCH_SELLER_ORDERS_FAILURE';